"""
store.py — Postgres (Supabase) persistence layer.

Migrated from SQLite to Supabase Postgres. To keep every caller unchanged, this
module exposes a thin compatibility shim over psycopg (v3) so the rest of the
codebase keeps writing sqlite-style SQL:

  • `?` placeholders are translated to psycopg's `%s` on the fly.
  • Literal `%` (e.g. LIKE '%theme%') is escaped only when params are bound.
  • Rows behave like sqlite3.Row — subscriptable by BOTH column name and index,
    plus dict methods (.get/.keys) since some callers rely on those.

The public surface (get_db, migrate, upsert_account, upsert_tweet,
insert_mention, log_run, log_roster_change) is identical to the old SQLite
version, so fetch/analyze/report code did not change.

Connection is read from DATABASE_URL (Supabase pooler URI, port 6543).
`prepare_threshold=None` disables server-side prepared statements, which the
transaction-mode pooler (pgbouncer) does not support.
"""

import os

import psycopg
from dotenv import load_dotenv

load_dotenv()


def _dsn():
    dsn = os.getenv("DATABASE_URL")
    if not dsn:
        raise RuntimeError("DATABASE_URL not set (Supabase Postgres connection string)")
    return dsn


# Postgres schema. Mirrors the live SQLite DB including columns that drifted in
# over time: accounts.tweet_cap_override, tweets.has_theme_word, and the themes
# table. AUTOINCREMENT integer PKs become IDENTITY; GENERATED BY DEFAULT (not
# ALWAYS) so the one-off migration can insert explicit id values.
_SCHEMA = """
CREATE TABLE IF NOT EXISTS accounts (
    user_id          TEXT PRIMARY KEY,
    username         TEXT NOT NULL,
    display_name     TEXT,
    followers        INTEGER,
    following        INTEGER,
    is_blue_verified INTEGER DEFAULT 0,
    source           TEXT,
    active           INTEGER DEFAULT 1,
    added_at         TEXT NOT NULL,
    last_seen_at     TEXT NOT NULL,
    tweet_cap_override INTEGER
);

CREATE TABLE IF NOT EXISTS tweets (
    id            TEXT PRIMARY KEY,
    user_id       TEXT NOT NULL REFERENCES accounts(user_id),
    text          TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    like_count    INTEGER DEFAULT 0,
    retweet_count INTEGER DEFAULT 0,
    reply_count   INTEGER DEFAULT 0,
    view_count    INTEGER DEFAULT 0,
    fetched_at    TEXT NOT NULL,
    has_theme_word INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mentions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tweet_id    TEXT NOT NULL REFERENCES tweets(id),
    ticker      TEXT NOT NULL,
    week_start  TEXT NOT NULL,
    sentiment   TEXT,
    conviction  INTEGER,
    rationale   TEXT,
    scored_at   TEXT
);

CREATE TABLE IF NOT EXISTS weekly_runs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_at              TEXT NOT NULL,
    week_start          TEXT NOT NULL,
    accounts_fetched    INTEGER DEFAULT 0,
    tweets_fetched      INTEGER DEFAULT 0,
    mentions_extracted  INTEGER DEFAULT 0,
    api_cost_usd        DOUBLE PRECISION DEFAULT 0.0,
    status              TEXT NOT NULL,
    notes               TEXT
);

CREATE TABLE IF NOT EXISTS roster_changes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    TEXT NOT NULL,
    change_type TEXT NOT NULL,
    reason      TEXT,
    changed_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS themes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label        TEXT NOT NULL,
    theme        TEXT NOT NULL,
    narrative    TEXT,
    tickers      TEXT,
    accounts     TEXT,
    extracted_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tweets_created  ON tweets(created_at);
CREATE INDEX IF NOT EXISTS idx_mentions_ticker ON mentions(ticker);
"""


# ── sqlite-compat shim ────────────────────────────────────────────────────────

class _Row(dict):
    """
    Row that mimics sqlite3.Row: subscriptable by column name AND by integer
    position, while remaining a full dict (so .get()/.keys()/dict(row) work).
    """
    __slots__ = ("_values",)

    def __init__(self, columns, values):
        super().__init__(zip(columns, values))
        self._values = list(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)


def _row_factory(cursor):
    desc = cursor.description
    columns = [c.name for c in desc] if desc else []

    def make(values):
        return _Row(columns, values)

    return make


def _translate(sql, params):
    # Escape literal % only when params are bound (psycopg only interpolates
    # then); otherwise `?` -> `%s`. Escaping must precede `?` substitution so
    # the generated `%s` is not itself doubled.
    if params:
        sql = sql.replace("%", "%%")
    return sql.replace("?", "%s")


class _Conn:
    """Wraps a psycopg connection so callers keep using sqlite-style calls."""

    def __init__(self, conn):
        self._conn = conn

    def execute(self, sql, params=None):
        q = _translate(sql, params)
        if params is None:
            return self._conn.execute(q)
        return self._conn.execute(q, params)

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()


# ── public API (unchanged surface) ────────────────────────────────────────────

def migrate():
    with get_db() as conn:
        conn.execute(_SCHEMA)


class get_db:
    """
    Context manager yielding a sqlite-compatible connection.

    Commits on clean exit, rolls back on exception, always closes — identical
    semantics to the old sqlite get_db(), so `with store.get_db() as conn:`
    blocks throughout the codebase are unchanged.
    """

    def __enter__(self):
        self._raw = psycopg.connect(
            _dsn(),
            row_factory=_row_factory,
            autocommit=False,
            prepare_threshold=None,
            connect_timeout=15,
        )
        self._conn = _Conn(self._raw)
        return self._conn

    def __exit__(self, exc_type, exc, tb):
        try:
            if exc_type is None:
                self._raw.commit()
            else:
                self._raw.rollback()
        finally:
            self._raw.close()
        return False


# ── CRUD helpers ──────────────────────────────────────────────────────────────

def upsert_account(conn, user_id, username, display_name=None, followers=None,
                   following=None, is_blue_verified=0, source=None, now=None):
    from datetime import datetime, timezone
    ts = now or datetime.now(timezone.utc).isoformat()
    conn.execute("""
        INSERT INTO accounts (user_id, username, display_name, followers, following,
                              is_blue_verified, source, added_at, last_seen_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(user_id) DO UPDATE SET
            username        = excluded.username,
            display_name    = excluded.display_name,
            followers       = excluded.followers,
            following       = excluded.following,
            is_blue_verified = excluded.is_blue_verified,
            last_seen_at    = excluded.last_seen_at
    """, (user_id, username, display_name, followers, following,
          is_blue_verified, source, ts, ts))


def upsert_tweet(conn, tweet_id, user_id, text, created_at,
                 like_count=0, retweet_count=0, reply_count=0,
                 view_count=0, fetched_at=None):
    from datetime import datetime, timezone
    ts = fetched_at or datetime.now(timezone.utc).isoformat()
    conn.execute("""
        INSERT INTO tweets (id, user_id, text, created_at, like_count,
                            retweet_count, reply_count, view_count, fetched_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
            like_count    = excluded.like_count,
            retweet_count = excluded.retweet_count,
            reply_count   = excluded.reply_count,
            view_count    = excluded.view_count
    """, (tweet_id, user_id, text, created_at, like_count,
          retweet_count, reply_count, view_count, ts))


def insert_mention(conn, tweet_id, ticker, week_start,
                   sentiment=None, conviction=None, rationale=None, scored_at=None):
    conn.execute("""
        INSERT INTO mentions (tweet_id, ticker, week_start, sentiment,
                              conviction, rationale, scored_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (tweet_id, ticker, week_start, sentiment, conviction, rationale, scored_at))


def log_run(conn, run_at, week_start, accounts_fetched=0, tweets_fetched=0,
            mentions_extracted=0, api_cost_usd=0.0, status="success", notes=None):
    conn.execute("""
        INSERT INTO weekly_runs (run_at, week_start, accounts_fetched,
                                 tweets_fetched, mentions_extracted,
                                 api_cost_usd, status, notes)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, (run_at, week_start, accounts_fetched, tweets_fetched,
          mentions_extracted, api_cost_usd, status, notes))


def log_roster_change(conn, username, change_type, reason=None, changed_at=None):
    from datetime import datetime, timezone
    ts = changed_at or datetime.now(timezone.utc).isoformat()
    conn.execute("""
        INSERT INTO roster_changes (username, change_type, reason, changed_at)
        VALUES (?, ?, ?, ?)
    """, (username, change_type, reason, ts))


migrate()
